name: Run Update Cron Job

on:
  schedule:
    - cron: "30 5 * * *"   # First run: 11:00 AM IST (5:30 UTC)
    - cron: "30 3 * * *"  # Second run: 9:00 PM IST (10:30 UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the Python version (e.g., 3.x)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync_jobs.py
        env:
          PSQL_KEY: ${{ secrets.PSQL_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: python sync_jobs.py
